"""
参数注解:
model_name:模型名字,这里使用的是resnet架构模型
no_models:表示参与联邦学习的模型的数量
type:指定数据集的类型
global_epochs:在全局模型训练的周期数
local_epochs:在本地模型上训练的周期数
k:在联邦学习中,每轮迭代用于更新全局模型的本地模型的数量
batch_size:训练时每个批次样本数量
momentum:动量
lambda:正则化参数
eta:某一个参数的权重因子
alpha:某一个参数的权重因子
poison_label:中毒的毒标签
posioning_per_batch:每个批次中毒药样本的数量
相当于HFL简洁版
配置和HFL相当
python3.7

"""